# Generated by Django 5.0.4 on 2024-04-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SubCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("perro", "Perro"),
                            ("gato", "Gato"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="productos/default.jpg",
                        null=True,
                        upload_to="productos",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_normal", models.IntegerField(default=0)),
                ("promocion", models.BooleanField(default=False)),
                ("descuento", models.IntegerField(default=0)),
                ("stock", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="Core.categoria",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="Core.subcategoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleCarrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("precio_unitario", models.IntegerField(default=0)),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="Core.carrito",
                    ),
                ),
                ("productos", models.ManyToManyField(to="Core.producto")),
            ],
        ),
        migrations.CreateModel(
            name="RegistroEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=200)),
                ("ciudad", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
                ("pais", models.CharField(max_length=200)),
                ("codigo_postal", models.CharField(max_length=200)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="Core.carrito",
                    ),
                ),
                (
                    "detalle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.detallecarrito",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Administrador"), ("cliente", "Cliente")],
                        max_length=20,
                    ),
                ),
                ("activo_subscripcion", models.BooleanField(default=False)),
                ("precio_subscripcion", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
